vars:
  version: &kb_version 'Ergogen Pteron36 v0.1'

units:
  # Key and keycap measures
  kx: u  # spacing between key centers (X-axis)
  ky: u  # spacing between key centers (X-axis)
  px: kx +4
  py: ky +4
  ks: 19  # horizontal space between columns (default: 19)
  kp: 19  # vertical padding between keys (deafult: 19)
  kcow: 14  # key cutout hole width (cherry: 14, choc: 13.8)
  kcoh: 14  # key cutout hole height (cherry: 14, choc: 13.8)
  keycw: 18  # keycap width (cherry: 18, choc: 17.5)
  keych: 18  # keycap height (cherry: 18, choc: 16.5)
  hand_rotation: 0
  hand_dist: 50
  
#trackpad settings
  trackpad_rad: 25
  trackpad_sx: 0
  trackpad_sy: -0.45py
  trackpad_rot: 180

#pro micro settings
  prmw: 18
  prmh: 35
  prm_sx: 0
  prm_sy: 0
  prm_rot: -90

# Physical measures
  screw_radius: 1.1  # M2 screws
  spacer_radius: 2.05  # M2 standoffs
  fillet_radius: 0.5

 # Thumb splay
  splay_thumb_middle: -15
  splay_thumb_far: -15

# screw measures
  m3_screw_radius: 3.4/2

points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
        rotate: 5
      columns:
        pinky:
          key.column_net: C1
          key.mirror.column_net: C10
        ring:
          key.splay: -5
          key.origin: [-12, -19]
          key.stagger: 15
          key.column_net: C2
          key.mirror.column_net: C9
        middle:
          key.stagger: 5
          key.column_net: C3
          key.mirror.column_net: C8
        index:
          key.stagger: -6
          key.column_net: C4
          key.mirror.column_net: C7
        inner:
          key.stagger: -2
          key.column_net: C5
          key.mirror.column_net: C6
      rows:
        bottom:
          row_net: R3
        home:
          row_net: R2
        top:
          row_net: R1
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [1, -20]
      columns:
        near:
          key.splay: -15
          key.origin: [-7, -5]
          key.column_net: C3
          key.mirror.column_net: C8
        home:
          key.splay: -15
          key.origin: [-9, -11]
          key.column_net: C4
          key.mirror.column_net: C7
        far:
          key.splay: -15
          key.origin: [-9, -11]
          key.column_net: C5
          key.mirror.column_net: C6
      rows:
        home:
          row_net: R4
  rotate: -20
  mirror: &mirror
    ref: matrix_inner_top
    distance: hand_dist
outlines:
  raw:
    - what: rectangle
      where: true
      size: [u,u]
  _switch_cutouts:
    - what: rectangle
      where: true
      size: [kcow, kcoh]
  _screws:
    - what: circle
      radius: m3_screw_radius
      adjust:
            ref: matrix_pinky_top
            shift: [0.1ks, 0.75 kp]
    - what: circle
      radius: m3_screw_radius
      adjust:
            ref: mirror_matrix_pinky_top
            shift: [0.1ks, 0.75 kp]
    - what: circle
      radius: m3_screw_radius
      adjust:
            ref: matrix_index_top
            shift: [-0.2ks, 0.7 kp]
    - what: circle
      radius: m3_screw_radius
      adjust:
            ref: mirror_matrix_index_top
            shift: [-0.2ks, 0.7 kp]
    - what: circle
      radius: m3_screw_radius
      adjust:
            ref: matrix_middle_bottom
            shift: [0, -0.7 kp]
    - what: circle
      radius: m3_screw_radius
      adjust:
            ref: mirror_matrix_middle_bottom
            shift: [0, -0.7 kp]
    - what: circle
      radius: m3_screw_radius
      where:
          aggregate.parts:
            - ref: thumbfan_far_home
            - ref: mirror_thumbfan_far_home
    - what: circle
      radius: m3_screw_radius
      where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [prm_sx, prm_sy]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  promicro:
    - what: rectangle
      size: [prmh,prmw]
      where:
        aggregate.parts:
          - ref: matrix_inner_top
          - ref: mirror_matrix_inner_top
        shift: [prm_sx, prm_sy]
        rotate: prm_rot
    
  cirque_add:
    - what: circle
      radius: trackpad_rad
      where:
          aggregate.parts:
            - ref: matrix_inner_bottom
            - ref: mirror_matrix_inner_bottom
          shift: [trackpad_sx, trackpad_sy]
          rotate: trackpad_rot
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [0.45px,0.5py]
        - ref: matrix_inner_top
          shift: [0.275px,1py]

        - ref: mirror_matrix_inner_top
          shift: [0.275px,1py]
        - ref: mirror_matrix_inner_top
          shift: [0.45px,0.5py]  
        
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_matrix_ring_bottom
          shift: [-0.35px,-0.5py]
        - ref: mirror_matrix_index_bottom
          shift: [0.5px,-0.6py]
        - ref: mirror_thumbfan_near_home
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbfan_near_home
          shift: [0.4px,-0.5py]
        - ref: mirror_thumbfan_home_home
          shift: [0.4px,-0.5py]
        - ref: mirror_thumbfan_far_home
          shift: [0.5px,-0.5py]
        - ref: mirror_thumbfan_far_home
          shift: [0.5px,0.42py]
        - ref: thumbfan_far_home
          shift: [0.5px,0.42py]
        - ref: thumbfan_far_home
          shift: [0.5px,-0.5py]
        - ref: thumbfan_home_home
          shift: [0.4px,-0.5py]
        - ref: thumbfan_near_home
          shift: [0.4px,-0.5py]
        - ref: thumbfan_near_home
          shift: [-0.5px,-0.5py]
        - ref: matrix_index_bottom
          shift: [0.5px,-0.6py]
        - ref: matrix_ring_bottom
          shift: [-0.35px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
       
      fillet: 1
  preview:
    - what: outline
      name: board
    - what: outline
      name: keys
      operation: stack
    - what: outline
      name: cirque_add
      operation: stack
    - what: outline
      name: promicro
      operation: stack
    - what: outline
      name: _screws
      operation: stack

  pcb_board:
    - what: outline
      name: board
    - what: outline
      name: _screws
      operation: subtract

pcbs:  
  ergogen_pteron36_super:
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: mx_socket_mxlp_choc
        where: true
        params:
          from: "{{row_net}}"
          to: "{{column_net}}"
      mcu:
        what: promicro
        params:
          P2: SDA
          P3: SCL
          P21: R1
          P20: R2
          P19: R3
          P18: C5
          P4: R4
          P5: C6
          P6: C7
          P7: C8
          P8: C9
          P9: C10
          P10: C1
          P16: C2
          P14: C3
          P15: C4
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [prm_sx, prm_sy]
          rotate: prm_rot
      fc:
        what: fh12_12
        params:
          P1: VCC
          P2: GND
          P3: SDA
          P4: SCL
        where:
          aggregate.parts:
            - ref: matrix_inner_bottom
            - ref: mirror_matrix_inner_bottom
          shift: [trackpad_sx, trackpad_sy]
          rotate: trackpad_rot
      res_sda:
        what: r_0805
        params:
          P1: VCC
          P2: SDA
        where:
          aggregate.parts:
            - ref: matrix_inner_bottom
            - ref: mirror_matrix_inner_bottom
          shift: [trackpad_sx+8.5, trackpad_sy]
          rotate: 90
      res_scl:
        what: r_0805
        params:
          P1: VCC
          P2: SCL
        where:
          aggregate.parts:
            - ref: matrix_inner_bottom
            - ref: mirror_matrix_inner_bottom
          shift: [trackpad_sx-8.5, trackpad_sy]
          rotate: 90
      jumper_f:
        what: jumper
        params:
          from: RST
          to: GND
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [12, 0]
          rotate: -90
      jumper_b:
        what: jumper
        params:
          from: RST
          to: GND
          side: 'B'
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [12, 0]
          rotate: -90
