vars:
  version: &kb_version 'Ergogen Pteron36 v0.1'

units:
  # Key and keycap measures
  kx: u  # spacing between key centers (X-axis)
  ky: u  # spacing between key centers (X-axis)
  px: kx + 4
  py: ky + 4
  ks: 19  # horizontal space between columns (default: 19)
  kp: 19  # vertical padding between keys (deafult: 19)
  kcow: 14  # key cutout hole width (cherry: 14, choc: 13.8)
  kcoh: 14  # key cutout hole height (cherry: 14, choc: 13.8)
  keycw: 18  # keycap width (cherry: 18, choc: 17.5)
  keych: 18  # keycap height (cherry: 18, choc: 16.5)
  hand_rotation: 0

  # Physical measures
  screw_radius: 1.1  # M2 screws
  spacer_radius: 2.05  # M2 standoffs
  fillet_radius: 0.5

  # Thumb splay
  splay_thumb_middle: -15
  splay_thumb_far: -15
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
        rotate: 5
      columns:
        pinky:
          key.column_net: C1
          key.mirror.column_net: C10
        ring:
          key.splay: -5
          key.origin: [-12, -19]
          key.stagger: 15
          key.column_net: C2
          key.mirror.column_net: C9
        middle:
          key.stagger: 5
          key.column_net: C3
          key.mirror.column_net: C8
        index:
          key.stagger: -6
          key.column_net: C4
          key.mirror.column_net: C7
        inner:
          key.stagger: -2
          key.column_net: C5
          key.mirror.column_net: C6
      rows:
        bottom:
          row_net: R3
        home:
          row_net: R2
        top:
          row_net: R1
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [1, -20]
      columns:
        near:
          key.splay: -15
          key.origin: [-7, -5]
          key.column_net: C3
          key.mirror.column_net: C8
        home:
          key.splay: -15
          key.origin: [-9, -11]
          key.column_net: C4
          key.mirror.column_net: C7
        far:
          key.splay: -15
          key.origin: [-9, -11]
          key.column_net: C5
          key.mirror.column_net: C6
      rows:
        home:
          row_net: R4
  rotate: -20
  mirror: &mirror
    ref: matrix_pinky_home
    distance: 240
outlines:
  raw:
    - what: rectangle
      where: true
      size: [u,u]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_matrix_ring_bottom
          shift: [-0.35px,-0.5py]
        - ref: mirror_matrix_index_bottom
          shift: [0.5px,-0.6py]
        - ref: mirror_thumbfan_near_home
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbfan_near_home
          shift: [0.4px,-0.5py]
        - ref: mirror_thumbfan_home_home
          shift: [0.4px,-0.5py]
        - ref: mirror_thumbfan_far_home
          shift: [0.5px,-0.5py]
        - ref: mirror_thumbfan_far_home
          shift: [0.5px,0.42py]
        - ref: thumbfan_far_home
          shift: [0.5px,0.42py]
        - ref: thumbfan_far_home
          shift: [0.5px,-0.5py]
        - ref: thumbfan_home_home
          shift: [0.4px,-0.5py]
        - ref: thumbfan_near_home
          shift: [0.4px,-0.5py]
        - ref: thumbfan_near_home
          shift: [-0.5px,-0.5py]
        - ref: matrix_index_bottom
          shift: [0.5px,-0.6py]
        - ref: matrix_ring_bottom
          shift: [-0.35px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
       
      fillet: 2
  combo:
    - name: board
    - operation: subtract
      name: keys

pcbs:  
  ergogen_pteron36_super:
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: mx_socket_mxlp_choc
        where: true
        params:
          from: "{{row_net}}"
          to: "{{column_net}}"
      mcu:
        what: promicro
        params:
          P2: SDA
          P3: SCL
          P21: R1
          P20: R2
          P19: R3
          P18: R4
          P4: C1
          P5: C2
          P6: C3
          P7: C4
          P8: C5
          P9: C6
          P10: C7
          P16: C8
          P14: C9
          P15: C10
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [0, -14]
          rotate: -90
      fc:
        what: fh12_12
        params:
          P1: VCC
          P2: GND
          P3: SDA
          P4: SCL
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [0, -57.5]
          rotate: 180
      res_sda:
        what: r_0805
        params:
          P1: VCC
          P2: SDA
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [8.5, -57.5]
          rotate: 90
      res_scl:
        what: r_0805
        params:
          P1: VCC
          P2: SCL
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [-8.5, -57.5]
          rotate: 90
      jumper_f:
        what: jumper
        params:
          from: RST
          to: GND
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [15, 0]
          rotate: -90
      jumper_b:
        what: jumper
        params:
          from: RST
          to: GND
          side: 'B'
        where:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [15, 0]
          rotate: -90
